import SwiftUI
import SwiftData
import PhotosUI
import UIKit
struct StatsView:View{@Query var routes:[Route];@Query var shifts:[Shift];var body:some View{ScrollView{VStack(spacing:14){KXHeader(title:"Статистика",subtitle:"Удалённые трассы не учитываются");KXCard{Text("\(routes.filter{$0.deletedAt==nil}.reduce(0){$0+$1.factualOrders}) заказов").font(.largeTitle.bold());Text("\(routes.filter{$0.deletedAt==nil}.count) колечек · \(shifts.filter{$0.deletedAt==nil}.count) смен").foregroundStyle(.secondary)}}.padding(18)}}}
struct ScannerView:View{@Environment(\.modelContext)var ctx;@Query(sort:\Shift.date,order:.reverse)var shifts:[Shift];@State var mode = Mode.route;@State var photos:[PhotosPickerItem] = [];@State var recognized = "";@State var type = RouteType.ot;@State var orders = "";@State var km = "";@State var customers:[CustomerDraft] = [];@State var financeAmount = "";enum Mode:String,CaseIterable,Identifiable{case route = "Трасса",customers = "Заказники",stats = "Статистика курьера",finance = "Бонусы / штрафы";var id:String{rawValue}};var active:Shift?{shifts.first{$0.status == .active && $0.deletedAt==nil}};var body:some View{ScrollView{VStack(spacing:12){KXHeader(title:"Сканер",subtitle:"Каждый тип экрана распознаётся отдельно");ForEach(Mode.allCases){m in Button(m.rawValue){mode = m;recognized = "";customers = []}.buttonStyle(.borderedProminent).tint(mode==m ? Color.kxPurple:Color.kxSurface2)};PhotosPicker(selection:$photos,maxSelectionCount:8,matching:.images){Text("Галерея / фото").frame(maxWidth:.infinity)}.buttonStyle(.borderedProminent).tint(Color.kxGreen);if mode == .route{Picker("Тип",selection:$type){ForEach(RouteType.allCases){Text($0.rawValue).tag($0)}}.pickerStyle(.segmented);TextField("Количество заказов",text:$orders).keyboardType(.numberPad).textFieldStyle(.roundedBorder);TextField("Километраж",text:$km).keyboardType(.decimalPad).textFieldStyle(.roundedBorder);Text("Итог по трассе и чаевые рассчитываются автоматически.").foregroundStyle(.secondary);Button("Сохранить закрытую трассу"){saveRoute()}.buttonStyle(.borderedProminent).tint(Color.kxGreen).disabled(active==nil)}else if mode == .customers{Button("Добавить клиента вручную"){customers.append(.init())}.buttonStyle(.bordered);ForEach($customers){$c in KXCard{VStack{TextField("Имя",text:$c.first).textFieldStyle(.roundedBorder);TextField("Фамилия",text:$c.last).textFieldStyle(.roundedBorder);TextField("Адрес",text:$c.address).textFieldStyle(.roundedBorder)}}};if !customers.isEmpty{Button("Добавить \(customers.count) клиентов"){saveCustomers()}.buttonStyle(.borderedProminent).tint(Color.kxGreen)}}else if mode == .finance{TextField("Сумма Kč",text:$financeAmount).keyboardType(.decimalPad).textFieldStyle(.roundedBorder);HStack{Button("Бонус / компенсация"){saveFinance(.bonus)}.buttonStyle(.borderedProminent).tint(Color.kxGreen);Button("Штраф"){saveFinance(.penalty)}.buttonStyle(.bordered).tint(.red)}}else{if !recognized.isEmpty{KXCard{Text(recognized).font(.caption).textSelection(.enabled)}}}}.padding(18)}.toolbar{KeyboardDoneToolbar()}.onChange(of:photos){_,items in Task{var blocks:[String] = [];for item in items{if let data = try? await item.loadTransferable(type:Data.self),let im = UIImage(data:data),let t = try? await OCRService.recognize(im){blocks.append(t)}};recognized = blocks.joined(separator:"\n");if mode == .customers{customers = parseCustomers(recognized)}}}}
 func saveRoute(){guard let s = active else{return};let seq = (try? ctx.fetch(FetchDescriptor<Route>()).filter{$0.shiftID==s.id}.count) ?? 0;ctx.insert(Route(shiftID:s.id,sequence:seq+1,type:type,warehouse:s.warehouse,factualOrders:Int(orders) ?? 0,distanceKm:Double(km.replacingOccurrences(of:",",with:"."))));try? ctx.save();orders = "";km = ""}
 func parseCustomers(_ text:String)->[CustomerDraft]{text.components(separatedBy:.newlines).filter{!$0.trimmingCharacters(in:.whitespaces).isEmpty}.prefix(50).map{line in var d = CustomerDraft();let parts = line.split(separator:" ");d.first = parts.first.map(String.init) ?? "";d.address = parts.dropFirst().joined(separator:" ");return d}}
 func saveCustomers(){for d in customers where !d.first.isEmpty || !d.address.isEmpty{ctx.insert(Customer(firstName:d.first,lastName:d.last,address:d.address))};try? ctx.save();customers = []}
 func saveFinance(_ k:FinancialKind){let h = Int64((Double(financeAmount.replacingOccurrences(of:",",with:".")) ?? 0)*100);ctx.insert(FinancialEntry(kind:k,amountHellers:h,note:recognized,source:photos.isEmpty ? "Ручной ввод":"OCR"));try? ctx.save();financeAmount = "";recognized = ""}
}
struct CustomerDraft:Identifiable{let id = UUID();var first = "";var last = "";var address = ""}
