import Foundation
import FirebaseCore
import FirebaseAuth
import FirebaseFirestore
import CryptoKit
import UIKit
@MainActor final class SessionStore:ObservableObject{
 @Published var state:State = .loading;@Published var profile:UserProfile?;@Published var isOwner = false;enum State:Equatable{case loading,needsFirebase,registration,active,frozen,revoked,owner};private var listener:ListenerRegistration?;let ownerUID = "dDUHublQoTccwtzPa1hmpyiDTd23";init(){Task{await bootstrap()}}
 func bootstrap()async{guard FirebaseApp.app() != nil else{state = .needsFirebase;return};if let u = Auth.auth().currentUser,u.uid==ownerUID{isOwner = true;state = .owner;return};if Auth.auth().currentUser==nil{do{_ = try await Auth.auth().signInAnonymously()}catch{state = .registration;return}};guard let uid = Auth.auth().currentUser?.uid else{state = .registration;return};listen(uid)}
 private func listen(_ uid:String){listener?.remove();listener = Firestore.firestore().collection("users").document(uid).addSnapshotListener{[weak self] snap,_ in Task{@MainActor in guard let self else{return};guard let d = snap?.data()else{self.state = .registration;return};self.profile = UserProfile(d);switch d["status"] as? String ?? ""{case "ACTIVE":self.state = .active;case "FROZEN":self.state = .frozen;default:self.state = .revoked}}}}
 func activate(firstName:String,lastName:String,courierID:String,key:String)async throws{if Auth.auth().currentUser==nil{_ = try await Auth.auth().signInAnonymously()};guard let uid = Auth.auth().currentUser?.uid else{throw LicenseError.noUser};let n = key.uppercased().filter{$0.isLetter||$0.isNumber};guard n.hasPrefix("KX"),n.count==14 else{throw LicenseError.badFormat};let hash = SHA256.hash(data:Data(n.utf8)).map{String(format:"%02x",$0)}.joined();let db = Firestore.firestore();let kr = db.collection("activation_keys").document(hash);let dr = db.collection("devices").document(Self.deviceID());let ur = db.collection("users").document(uid);_ = try await db.runTransaction{tx,ep in do{let kd = try tx.getDocument(kr);guard kd.exists,kd.data()?["status"] as? String=="UNUSED" else{throw LicenseError.invalidKey};let now = FieldValue.serverTimestamp();tx.updateData(["status":"USED","userId":uid,"deviceId":Self.deviceID(),"activatedAt":now],forDocument:kr);tx.setData(["uid":uid,"firstName":firstName,"lastName":lastName,"courierId":courierID,"deviceId":Self.deviceID(),"status":"ACTIVE","role":"USER","createdAt":now,"updatedAt":now],forDocument:ur);tx.setData(["uid":uid,"deviceId":Self.deviceID(),"platform":"ANDROID","manufacturer":"Apple","model":UIDevice.current.model,"androidVersion":"iOS \(UIDevice.current.systemVersion)","status":"ACTIVE","createdAt":now,"lastSeenAt":now],forDocument:dr);return nil}catch{ep?.pointee = error as NSError;return nil}};listen(uid)}
 func ownerLogin(email:String,password:String)async throws{listener?.remove();try? Auth.auth().signOut();let r = try await Auth.auth().signIn(withEmail:email,password:password);guard r.user.uid==ownerUID else{try? Auth.auth().signOut();throw LicenseError.notOwner};isOwner = true;state = .owner}
 func leaveOwnerToActivation()async{listener?.remove();try? Auth.auth().signOut();isOwner = false;profile = nil;do{_ = try await Auth.auth().signInAnonymously()}catch{};state = .registration}
 func signOutUser()async{await leaveOwnerToActivation()}
 static func deviceID()->String{let s = UIDevice.current.identifierForVendor?.uuidString ?? UUID().uuidString;return SHA256.hash(data:Data(("IOS|"+s).utf8)).map{String(format:"%02x",$0)}.joined()}
}
struct UserProfile{let firstName:String,lastName:String,courierID:String,status:String;init(_ d:[String:Any]){firstName = d["firstName"] as? String ?? "";lastName = d["lastName"] as? String ?? "";courierID = d["courierId"] as? String ?? "";status = d["status"] as? String ?? ""}}
enum LicenseError:LocalizedError{case noUser,badFormat,invalidKey,notOwner;var errorDescription:String?{switch self{case .noUser:return"Нет Firebase-сессии";case .badFormat:return"Ключ неверного формата";case .invalidKey:return"Ключ недействителен или уже использован";case .notOwner:return"Нет OWNER-доступа"}}}
